version: "3.8"

services:
  app:
    build: .
    container_name: mysqldump-cron
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file: .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /usr/bin/mysqldump:/usr/bin/mysqldump
